#!/bin/sh

### BEGIN INIT INFO
# Provides:          kibana
# Required-Start:    $local_fs $remote_fs $network
# Should-Start:      $time
# Required-Stop:     $local_fs $remote_fs $network
# Default-Start:     3 5
# Default-Stop:      0 1 2 6
# Short-Description: Kibana 4
# Description:       Service controller for Kibana 4
### END INIT INFO

INSTALLED_DIR=/usr/share/kibana
EXEC_SCRIPT="$INSTALLED_DIR/bin/kibana"
LOG_DIR=/var/log/kibana
PID_DIR=/var/run/kibana
PID_FILE="$PID_DIR"/kibana.pid
LOG_FILE="$LOG_DIR"/kibana.log
OUT_FILE="$LOG_DIR"/kibana.out
USER="kibana"
PROG="kibana"
LOCKFILE="/var/lock/subsys/$PROG"

test -d $LOG_DIR || mkdir $LOG_DIR

# Source function library.
. /etc/init.d/functions

RETVAL=0

case "$1" in
    start)
        running=`pidofproc -p $PID_FILE &> /dev/null`
        if [ ! "$running" ]; then
          echo -n "Starting $PROG"
          su -s /bin/bash $USER -c "nohup $EXEC_SCRIPT 0<&- &> $LOG_FILE & echo \$! > '$PID_FILE'"
          sleep 3
          pidofproc -p $PID_FILE &> /dev/null
          RETVAL=$?
          [ $RETVAL -eq 0 ] && touch $LOCKFILE
          [ $RETVAL -eq 0 ] && success || failure
        else
          echo -n "$PROG is already running"
          RETVAL=1
          failure
        fi
        echo
        ;;
    stop)
        if [ -f "$PID_FILE" ]; then
          echo -n "Stopping $PROG"
          killproc -p $PID_FILE $PROG
          RETVAL=$?
          [ $RETVAL -eq 0 ] && rm -f $LOCKFILE
          [ $RETVAL -eq 0 ] && success || failure
        else
          echo -n "$PROG is not running"
          RETVAL=1
          failure
        fi
        echo
        ;;
    restart)
        $0 stop
        $0 start
        ;;
    reload)
        $0 restart
        ;;
    status)
        status -p $PID_FILE $PROG
        RETVAL=$?
        ;;
*)
echo "Usage: $0 {start|stop|status|restart|reload}"
exit 1
;;
esac
exit $RETVAL